MutationSuccess:
    type: object
    config:
        fields:
            content:
                type: String!

Mutation:
  type: object
  config:
    fields:
      createProducts:
        type: "Products"
        resolve: '@=mutation("create_products", [args])'
        args:
          input:
            type: "ProductsInput"

      NewAstronaut:
        type: MutationSuccess
        resolve: "@=mutation('NewAstronaut', [args['input']['pseudo'], args['input']['grade']])"
        args:
          input:
            type: AstronautInput!

      NewGrade:
        type: MutationSuccess
        resolve: "@=mutation('NewGrade', [args['input']['name']])"
        args:
          input:
            type: GradeInput!