Query:
    type: object
    config:
        fields:
            categories:
                type: Categories
                args:
                    id:
                        type: Int
                resolve: '@=resolver("App\\GraphQL\\Resolver\\CategoriesResolver::resolve", [args["id"]])'