version: '3.4'

services:

  app:
    
    build:
      context: ./
      dockerfile: ./.docker/app/Dockerfile

    env_file:
      - ./.docker/app/.env

    container_name: app

    ports:
      - 8000:8000

    volumes:
      - ./app:/var/www/html

    tty: true

    depends_on:
      - db
    

  db:

    build:
      context: ./
      dockerfile: ./.docker/db/Dockerfile

    env_file:
      - ./.docker/db/.env

    container_name: db

    ports: 
      - 3306:3306

    tty: true

    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
